### ISSUE TITLE
ClassNotFoundException when running in UnitTest

### ISSUE THREAD

**Issue by rekire** [MiniDNS/minidns#120]
I'm evaluating this library for a project and I started using it in a UnitTest, but it crashes:

```
WARNUNG: Exception in findDNSByReflection
java.lang.ClassNotFoundException: android.os.SystemProperties
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.minidns.dnsserverlookup.AndroidUsingReflection.getDnsServerAddresses(AndroidUsingReflection.java:37)
	at org.minidns.DnsClient.findDNS(DnsClient.java:253)
	at org.minidns.DnsClient.findDnsAddresses(DnsClient.java:309)
	at org.minidns.DnsClient.getServerAddresses(DnsClient.java:102)
	at org.minidns.DnsClient.query(DnsClient.java:147)
        ...
```

In my opinion you should check first if you are running on Android before executing Android specific code. I just want to quote the first sentence of the readme: _"MiniDNS [...] is a DNS library for Android **and Java SE**."_ A unit test falls in my opinion in that case.

I like the idea of fallback to a fixed DNS server, but why just one IPv4 and IPv6? Google has 2 of both and there are also public alternatives like 1.1.1.1 or 9.9.9.9

When I find some free time I will create a PR in order to fix that. If anyone else is quicker then go on, that part is no rocket science.

**Comment by rekire** [comment]
That code could detect if junit is present, however your solution is much better.
