### ISSUE TITLE
Getting DnssecValidationFailedException for non existing domain

### ISSUE THREAD

**Issue by rekire** [MiniDNS/minidns#121]
I'm playing with this lib and got an unexpected error in my test code. I get an DnssecValidationFailedException for non existing domain "github.xxx".

Here is my test code:
```kotlin
class DnsTest {
    enum class AddressStatus {
        valid,
        notRegistered,
        noMxRecord,
        unknown
    }

    @Test
    fun evaluating() {
        val cases = mapOf(
            "github.com" to AddressStatus.valid,
            "github.io" to AddressStatus.noMxRecord,
            "github.xxx" to AddressStatus.notRegistered,
        )
        cases.forEach { (domain, expected) ->
            val result = checkDomain(domain)
            assertEquals("Unexpected result for $domain", expected, result)
        }
    }

    private fun checkDomain(domain: String) : AddressStatus {
        return try {
            val result = DnssecResolverApi.INSTANCE.resolve<MX>(Question(domain, Record.TYPE.MX))
            when {
                result.wasSuccessful() && result.answersOrEmptySet.isEmpty() -> AddressStatus.noMxRecord
                result.wasSuccessful() && result.answersOrEmptySet.isNotEmpty() -> AddressStatus.valid
                result.responseCode == RESPONSE_CODE.NX_DOMAIN -> AddressStatus.notRegistered
                else -> AddressStatus.unknown
            }
        } catch (err: DnssecValidationFailedException) {
            println("Error: ${err.message}")
            AddressStatus.unknown
        } catch (t: IOException) {
            AddressStatus.unknown
        }
    }
}
```

I get the exception: `Unexpected result for github.xxx expected:<notRegistered> but was:<unknown>`

When I run `dig github.xxx +dnssec` I get the expected NXDOMAIN status:
```
; <<>> DiG 9.10.6 <<>> github.xxx +dnssec
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 51158
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 8, ADDITIONAL: 1
```

**Comment by rekire** [comment]
I added a `err.printStackTrace()` like to generate this output:

```
Error: Validation of 1 NSEC3 record failed: Signature is invalid.
org.minidns.dnssec.DnssecValidationFailedException: Validation of 1 NSEC3 record failed: Signature is invalid.
	at org.minidns.dnssec.Verifier.verify(Verifier.java:76)
	at org.minidns.dnssec.DnssecClient.verifySignedRecords(DnssecClient.java:396)
	at org.minidns.dnssec.DnssecClient.verifySignatures(DnssecClient.java:321)
	at org.minidns.dnssec.DnssecClient.verifyNsec(DnssecClient.java:260)
	at org.minidns.dnssec.DnssecClient.verify(DnssecClient.java:151)
	at org.minidns.dnssec.DnssecClient.performVerification(DnssecClient.java:115)
	at org.minidns.dnssec.DnssecClient.queryDnssec(DnssecClient.java:105)
	at org.minidns.hla.DnssecResolverApi.resolve(DnssecResolverApi.java:65)
	at eu.rekisoft.android.editmail.DnsTest.checkDomain(DnsTest.kt:36)
	at eu.rekisoft.android.editmail.DnsTest.evaluating(DnsTest.kt:29)
```

**Comment by Flowdalic** [comment]
It appears there are invalid NSEC RRs for .xxx, together with valid ones. MiniDNS does throw a `DnssecValidationFailedException` as soon as it can not verify the signature for a NSEC record. I assume dig simply checks if there is at least a valid one. If my current, preliminary, assessment is correct, then this behavior could be changed (or at least made configurable) to match dig's behavior.
