### ISSUE TITLE
Probable IPv6 network malfunction - but how I do I work around it?

### ISSUE THREAD

**Issue by daniele-athome** [MiniDNS/minidns#80]
I have this stacktrace from a user of my Android app (sorry, very long repeated long lines):

```
2018-04-01 15:36:31 E/MessageCenterService: org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'beta.kontalk.net:5222' failed because: de.measite.minidns.util.MultipleIoException: sendto failed: ENETUNREACH (Network is unreachable), failed to connect to ns2.digitalocean.com/2400:cb00:2049:1::adf5:3b29 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to ns1.digitalocean.com/2400:cb00:2049:1::adf5:3a33 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to ns3.digitalocean.com/2400:cb00:2049:1::c629:dead (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to a.dns.it/2001:678:12:0:194:0:16:215 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to m.dns.it/2001:1ac0:0:200:0:a5d1:6004:2 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to r.dns.it/2001:760:ffff:ffff::ca (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to s.dns.it/2001:67c:1010:7::53 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to dns.nic.it/2a00:d40:1:1::5 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to nameserver.cnr.it/2a00:1620:c0:220:194:119:192:34 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to a.root-servers.net/2001:503:ba3e::2:30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to a.dns.it/2001:678:12:0:194:0:16:215 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to s.dns.it/2001:67c:1010:7::53 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to m.dns.it/2001:1ac0:0:200:0:a5d1:6004:2 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to r.dns.it/2001:760:ffff:ffff::ca (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to dns.nic.it/2a00:d40:1:1::5 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to nameserver.cnr.it/2a00:1620:c0:220:194:119:192:34 (port 53) after 5000ms: connect failed: ENETUNREACH 
(Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to d.root-servers.net/2001:500:2d::d (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to a.gtld-servers.net/2001:503:a83e::2:30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to b.gtld-servers.net/2001:503:231d::2:30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to k.gtld-servers.net/2001:503:d2d::30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to f.gtld-servers.net/2001:503:d414::30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to j.gtld-servers.net/2001:502:7094::30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to h.gtld-servers.net/2001:502:8cc::30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to e.gtld-servers.net/2001:502:1ca1::30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to i.gtld-servers.net/2001:503:39c1::30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to m.gtld-servers.net/2001:501:b1f9::30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to c.gtld-servers.net/2001:503:83eb::30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to d.gtld-servers.net/2001:500:856e::30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to l.gtld-servers.net/2001:500:d937::30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), Resolution loop detected, Resolution loop detected, sendto failed: ENETUNREACH (Network is unreachable), failed to connect to g.gtld-servers.net/2001:503:eea3::30 (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), sendto failed: ENETUNREACH (Network is unreachable), failed to connect to f.root-servers.net/2001:500:2f::f (port 53) after 5000ms: connect failed: ENETUNREACH (Network is unreachable), 'beta.kontalk.net:5222' failed because: de.measite.minidns.MiniDNSException$NullResultException: The request yielded a 'null' result while resolving.
	at org.kontalk.client.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:619)
	at org.kontalk.client.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:902)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:380)
```

I use SRV records for my XMPP host (beta.kontalk.net), in the log lines above it's trying to solve "beta.kontalk.net" directly but I have also other log lines trying to solve the SRV record with the same error messages.

It happens to this person only on a specific mobile network area, I understand it's probably an IPv6 malfunction, but how I can work around this? Is there a way to make the MiniDNS resolver use IPv4 name servers (and consequently use A records instead of AAAA records)? I can't find any useful option in Smack.

Thanks!

**Comment by daniele-athome** [comment]
Found it!

```
AbstractDNSClient.setPreferedIpVersion(AbstractDNSClient.IpVersionSetting.v4only);
```
